name = "TropicalHomotopyContinuation"
uuid = "291d046c-3347-11e9-1e74-c3d251d406c6"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"

[extras]
PolynomialTestSystems = "4c526841-e1e8-562c-bfa9-9f39d642e243"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PolynomialTestSystems", "Test"]
